# Generated by Django 5.1.5 on 2025-01-25 02:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoBodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=255, unique=True)),
                ('metros_cuadrados', models.PositiveIntegerField()),
                ('preparada_quimicos', models.BooleanField(default=False)),
                ('preparada_organicos', models.BooleanField(default=False)),
                ('hermetica', models.BooleanField(default=False)),
                ('precio_mensual', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Cotizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.PositiveIntegerField(default=0)),
                ('bodegas', models.ManyToManyField(related_name='cotizaciones', to='cotizacion.bodega')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='bodega',
            name='tipo_bodega',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bodegas', to='cotizacion.tipobodega'),
        ),
    ]
